version: "3"
volumes:
  works:
    driver: local
services:
  app:
    image: ubudev:20.04
    build:
      context: ./docker
    hostname: ubudev-2004
    volumes:
      - "~/.ssh/id_rsa:/home/mine/.ssh/id_rsa"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "works:/home/mine/works"
    env_file:
      - server.env
    command: [ "tail", "-f", "/dev/null" ]
    init: true
