version: "3"
volumes:
  ubudev_works:
    external: true
services:
  save:
    image: ubudev/volume-backup:latest
    build:
      context: ./docker
    volumes:
      - "ubudev_works:/volume/works"
      - "./backup:/backup"
